<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <OutputType>Library</OutputType>
    <PackageId>Lmc.Metrics</PackageId>
    <Version>3.0.0</Version>
    <RepositoryUrl>https://stash.int.lmc.cz/projects/ARCHI/repos/fmetrics/browse</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src/Audience.fs" />
    <Compile Include="src/WebServer.fs" />
    <Compile Include="src/Prometheus.fs" />
    <Compile Include="src/State.fs" />
    <Compile Include="src/ResourceAvailability.fs" />
    <Compile Include="src/ServiceStatus.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Suave" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lmc.ErrorHandling" Version="1.0" />
    <PackageReference Include="Lmc.ServiceIdentification" Version="2.2" />
  </ItemGroup>

</Project>
