<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <OutputType>Library</OutputType>
    <PackageId>Lmc.Metrics</PackageId>
    <Version>3.4.0</Version>
    <RepositoryUrl>https://bitbucket.lmc.cz/projects/ARCHI/repos/fmetrics/browse</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="src/Audience.fs" />
    <Compile Include="src/WebServer.fs" />
    <Compile Include="src/Prometheus.fs" />
    <Compile Include="src/State.fs" />
    <Compile Include="src/ResourceAvailability.fs" />
    <Compile Include="src/ServiceStatus.fs" />
  </ItemGroup>

  <Import Project=".paket\Paket.Restore.targets" />
</Project>
